import './globals.css'
import { Inter } from 'next/font/google'
import WithProviders from '@/app/WithProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AdsGency AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-screen`}>
        <WithProviders>
          {children}
        </WithProviders>
      </body>
    </html>
  )
}
